# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kingdoms.rpc_generated.kingdoms.v1 import content_pb2 as kingdoms_dot_v1_dot_content__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kingdoms/v1/content_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContentStub:
    """Game content provider service (ext-aoe2techtree family): a content
    source process serves localized game catalog data (factions, maps) to
    svc-core. Content is immutable between game patches; the core caches it
    in Mongo/Redis and bot admins trigger a refresh on patch days. The
    upstream the ext process reads (vendored dataset, HTTP API, ...) is
    the provider's own concern — the core only ever sees this contract,
    so switching to another API source never touches the consumers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContentCapabilities = channel.unary_unary(
                '/kingdoms.v1.Content/GetContentCapabilities',
                request_serializer=kingdoms_dot_v1_dot_content__pb2.ContentCapabilitiesRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_content__pb2.ContentCapabilities.FromString,
                _registered_method=True)
        self.ListFactions = channel.unary_unary(
                '/kingdoms.v1.Content/ListFactions',
                request_serializer=kingdoms_dot_v1_dot_content__pb2.ListFactionsRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_content__pb2.FactionList.FromString,
                _registered_method=True)
        self.GetFactionContent = channel.unary_unary(
                '/kingdoms.v1.Content/GetFactionContent',
                request_serializer=kingdoms_dot_v1_dot_content__pb2.FactionContentRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_content__pb2.LocalizedContent.FromString,
                _registered_method=True)
        self.GetMapContent = channel.unary_unary(
                '/kingdoms.v1.Content/GetMapContent',
                request_serializer=kingdoms_dot_v1_dot_content__pb2.MapContentRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_content__pb2.LocalizedContent.FromString,
                _registered_method=True)


class ContentServicer:
    """Game content provider service (ext-aoe2techtree family): a content
    source process serves localized game catalog data (factions, maps) to
    svc-core. Content is immutable between game patches; the core caches it
    in Mongo/Redis and bot admins trigger a refresh on patch days. The
    upstream the ext process reads (vendored dataset, HTTP API, ...) is
    the provider's own concern — the core only ever sees this contract,
    so switching to another API source never touches the consumers.
    """

    def GetContentCapabilities(self, request, context):
        """Declare the provider identity and its supported game/locale surface.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFactions(self, request, context):
        """Every faction key the source knows (catalog reconciliation).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFactionContent(self, request, context):
        """One faction's localized content (name + game-provided help summary).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMapContent(self, request, context):
        """One map's localized content (name-only today).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContentCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContentCapabilities,
                    request_deserializer=kingdoms_dot_v1_dot_content__pb2.ContentCapabilitiesRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_content__pb2.ContentCapabilities.SerializeToString,
            ),
            'ListFactions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFactions,
                    request_deserializer=kingdoms_dot_v1_dot_content__pb2.ListFactionsRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_content__pb2.FactionList.SerializeToString,
            ),
            'GetFactionContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFactionContent,
                    request_deserializer=kingdoms_dot_v1_dot_content__pb2.FactionContentRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_content__pb2.LocalizedContent.SerializeToString,
            ),
            'GetMapContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMapContent,
                    request_deserializer=kingdoms_dot_v1_dot_content__pb2.MapContentRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_content__pb2.LocalizedContent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kingdoms.v1.Content', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kingdoms.v1.Content', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Content:
    """Game content provider service (ext-aoe2techtree family): a content
    source process serves localized game catalog data (factions, maps) to
    svc-core. Content is immutable between game patches; the core caches it
    in Mongo/Redis and bot admins trigger a refresh on patch days. The
    upstream the ext process reads (vendored dataset, HTTP API, ...) is
    the provider's own concern — the core only ever sees this contract,
    so switching to another API source never touches the consumers.
    """

    @staticmethod
    def GetContentCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kingdoms.v1.Content/GetContentCapabilities',
            kingdoms_dot_v1_dot_content__pb2.ContentCapabilitiesRequest.SerializeToString,
            kingdoms_dot_v1_dot_content__pb2.ContentCapabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kingdoms.v1.Content/ListFactions',
            kingdoms_dot_v1_dot_content__pb2.ListFactionsRequest.SerializeToString,
            kingdoms_dot_v1_dot_content__pb2.FactionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFactionContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kingdoms.v1.Content/GetFactionContent',
            kingdoms_dot_v1_dot_content__pb2.FactionContentRequest.SerializeToString,
            kingdoms_dot_v1_dot_content__pb2.LocalizedContent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMapContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kingdoms.v1.Content/GetMapContent',
            kingdoms_dot_v1_dot_content__pb2.MapContentRequest.SerializeToString,
            kingdoms_dot_v1_dot_content__pb2.LocalizedContent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
