# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kingdoms/v1/content.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'kingdoms/v1/content.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19kingdoms/v1/content.proto\x12\x0bkingdoms.v1\"\x1c\n\x1a\x43ontentCapabilitiesRequest\"N\n\x13\x43ontentCapabilities\x12\x14\n\x0cprovider_key\x18\x01 \x01(\t\x12\x10\n\x08game_key\x18\x02 \x01(\t\x12\x0f\n\x07locales\x18\x03 \x03(\t\"\x15\n\x13ListFactionsRequest\"#\n\x0b\x46\x61\x63tionList\x12\x14\n\x0c\x66\x61\x63tion_keys\x18\x01 \x03(\t\"<\n\x15\x46\x61\x63tionContentRequest\x12\x13\n\x0b\x66\x61\x63tion_key\x18\x01 \x01(\t\x12\x0e\n\x06locale\x18\x02 \x01(\t\"4\n\x11MapContentRequest\x12\x0f\n\x07map_key\x18\x01 \x01(\t\x12\x0e\n\x06locale\x18\x02 \x01(\t\"\x8a\x01\n\x10LocalizedContent\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x0e\n\x06locale\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x12\n\nsource_url\x18\x05 \x01(\t\x12\r\n\x05\x66ound\x18\x06 \x01(\x08\x12\x11\n\timage_url\x18\x07 \x01(\t2\xe2\x02\n\x07\x43ontent\x12\x63\n\x16GetContentCapabilities\x12\'.kingdoms.v1.ContentCapabilitiesRequest\x1a .kingdoms.v1.ContentCapabilities\x12J\n\x0cListFactions\x12 .kingdoms.v1.ListFactionsRequest\x1a\x18.kingdoms.v1.FactionList\x12V\n\x11GetFactionContent\x12\".kingdoms.v1.FactionContentRequest\x1a\x1d.kingdoms.v1.LocalizedContent\x12N\n\rGetMapContent\x12\x1e.kingdoms.v1.MapContentRequest\x1a\x1d.kingdoms.v1.LocalizedContentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kingdoms.v1.content_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTENTCAPABILITIESREQUEST']._serialized_start=42
  _globals['_CONTENTCAPABILITIESREQUEST']._serialized_end=70
  _globals['_CONTENTCAPABILITIES']._serialized_start=72
  _globals['_CONTENTCAPABILITIES']._serialized_end=150
  _globals['_LISTFACTIONSREQUEST']._serialized_start=152
  _globals['_LISTFACTIONSREQUEST']._serialized_end=173
  _globals['_FACTIONLIST']._serialized_start=175
  _globals['_FACTIONLIST']._serialized_end=210
  _globals['_FACTIONCONTENTREQUEST']._serialized_start=212
  _globals['_FACTIONCONTENTREQUEST']._serialized_end=272
  _globals['_MAPCONTENTREQUEST']._serialized_start=274
  _globals['_MAPCONTENTREQUEST']._serialized_end=326
  _globals['_LOCALIZEDCONTENT']._serialized_start=329
  _globals['_LOCALIZEDCONTENT']._serialized_end=467
  _globals['_CONTENT']._serialized_start=470
  _globals['_CONTENT']._serialized_end=824
# @@protoc_insertion_point(module_scope)
