# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from kingdoms.rpc_generated.kingdoms.v1 import game_pb2 as kingdoms_dot_v1_dot_game__pb2

GRPC_GENERATED_VERSION = "1.84.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in kingdoms/v1/game_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GameStub:
    """Game provider service (ADR-0020): an external game data provider process
    (ext-librematch, ext-aoe2lobby, ...) serves this contract to svc-core.
    The core never interprets provider-internal identifiers: match_ref,
    profile_id and faction_key are opaque strings at the contract level.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                "/kingdoms.v1.Game/GetCapabilities",
                request_serializer=kingdoms_dot_v1_dot_game__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_game__pb2.Capabilities.FromString,
                _registered_method=True)
        self.ResolveProfile = channel.unary_unary(
                "/kingdoms.v1.Game/ResolveProfile",
                request_serializer=kingdoms_dot_v1_dot_game__pb2.ResolveProfileRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_game__pb2.ResolveProfileResponse.FromString,
                _registered_method=True)
        self.StreamMatchEvents = channel.unary_stream(
                "/kingdoms.v1.Game/StreamMatchEvents",
                request_serializer=kingdoms_dot_v1_dot_game__pb2.StreamMatchEventsRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_game__pb2.MatchEvent.FromString,
                _registered_method=True)
        self.GetMatchResult = channel.unary_unary(
                "/kingdoms.v1.Game/GetMatchResult",
                request_serializer=kingdoms_dot_v1_dot_game__pb2.GetMatchResultRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_game__pb2.MatchResult.FromString,
                _registered_method=True)
        self.GetPlayerStats = channel.unary_unary(
                "/kingdoms.v1.Game/GetPlayerStats",
                request_serializer=kingdoms_dot_v1_dot_game__pb2.GetPlayerStatsRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_game__pb2.PlayerStats.FromString,
                _registered_method=True)
        self.GetMatchLinks = channel.unary_unary(
                "/kingdoms.v1.Game/GetMatchLinks",
                request_serializer=kingdoms_dot_v1_dot_game__pb2.GetMatchLinksRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_game__pb2.MatchLinks.FromString,
                _registered_method=True)
        self.GetMatchDetails = channel.unary_unary(
                "/kingdoms.v1.Game/GetMatchDetails",
                request_serializer=kingdoms_dot_v1_dot_game__pb2.GetMatchDetailsRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_game__pb2.MatchDetails.FromString,
                _registered_method=True)
        self.ListMaps = channel.unary_unary(
                "/kingdoms.v1.Game/ListMaps",
                request_serializer=kingdoms_dot_v1_dot_game__pb2.ListMapsRequest.SerializeToString,
                response_deserializer=kingdoms_dot_v1_dot_game__pb2.GameMaps.FromString,
                _registered_method=True)


class GameServicer:
    """Game provider service (ADR-0020): an external game data provider process
    (ext-librematch, ext-aoe2lobby, ...) serves this contract to svc-core.
    The core never interprets provider-internal identifiers: match_ref,
    profile_id and faction_key are opaque strings at the contract level.

    """

    def GetCapabilities(self, request, context):
        """Declare what this provider actually supports. The core degrades
        cleanly on anything absent (reference: ladder spec 1.2).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResolveProfile(self, request, context):
        """Resolve which mod user matches a game profile. Used for profile
        validation at registration and for match participant resolution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamMatchEvents(self, request, context):
        """Stream match lifecycle events (lobby_opened, lobby_closed,
        game_started, game_ended) for the matches this provider can see.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMatchResult(self, request, context):
        """Fetch the result of a finished game (winner, duration, map, factions).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPlayerStats(self, request, context):
        """Named stats blocks for a player profile (rendered by the platform
        adapter; the core never formats them).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMatchLinks(self, request, context):
        """Game action links (join/spectate/insights) as opaque label+url pairs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMatchDetails(self, request, context):
        """Full match details: map, slotinfo (per-slot state) and the raw
        game options (map size, speed, victory condition, ...).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMaps(self, request, context):
        """The maps this provider knows about for its game (catalog data).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            "GetCapabilities": grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=kingdoms_dot_v1_dot_game__pb2.CapabilitiesRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_game__pb2.Capabilities.SerializeToString,
            ),
            "ResolveProfile": grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveProfile,
                    request_deserializer=kingdoms_dot_v1_dot_game__pb2.ResolveProfileRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_game__pb2.ResolveProfileResponse.SerializeToString,
            ),
            "StreamMatchEvents": grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMatchEvents,
                    request_deserializer=kingdoms_dot_v1_dot_game__pb2.StreamMatchEventsRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_game__pb2.MatchEvent.SerializeToString,
            ),
            "GetMatchResult": grpc.unary_unary_rpc_method_handler(
                    servicer.GetMatchResult,
                    request_deserializer=kingdoms_dot_v1_dot_game__pb2.GetMatchResultRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_game__pb2.MatchResult.SerializeToString,
            ),
            "GetPlayerStats": grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerStats,
                    request_deserializer=kingdoms_dot_v1_dot_game__pb2.GetPlayerStatsRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_game__pb2.PlayerStats.SerializeToString,
            ),
            "GetMatchLinks": grpc.unary_unary_rpc_method_handler(
                    servicer.GetMatchLinks,
                    request_deserializer=kingdoms_dot_v1_dot_game__pb2.GetMatchLinksRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_game__pb2.MatchLinks.SerializeToString,
            ),
            "GetMatchDetails": grpc.unary_unary_rpc_method_handler(
                    servicer.GetMatchDetails,
                    request_deserializer=kingdoms_dot_v1_dot_game__pb2.GetMatchDetailsRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_game__pb2.MatchDetails.SerializeToString,
            ),
            "ListMaps": grpc.unary_unary_rpc_method_handler(
                    servicer.ListMaps,
                    request_deserializer=kingdoms_dot_v1_dot_game__pb2.ListMapsRequest.FromString,
                    response_serializer=kingdoms_dot_v1_dot_game__pb2.GameMaps.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            "kingdoms.v1.Game", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("kingdoms.v1.Game", rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Game:
    """Game provider service (ADR-0020): an external game data provider process
    (ext-librematch, ext-aoe2lobby, ...) serves this contract to svc-core.
    The core never interprets provider-internal identifiers: match_ref,
    profile_id and faction_key are opaque strings at the contract level.

    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kingdoms.v1.Game/GetCapabilities",
            kingdoms_dot_v1_dot_game__pb2.CapabilitiesRequest.SerializeToString,
            kingdoms_dot_v1_dot_game__pb2.Capabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kingdoms.v1.Game/ResolveProfile",
            kingdoms_dot_v1_dot_game__pb2.ResolveProfileRequest.SerializeToString,
            kingdoms_dot_v1_dot_game__pb2.ResolveProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMatchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/kingdoms.v1.Game/StreamMatchEvents",
            kingdoms_dot_v1_dot_game__pb2.StreamMatchEventsRequest.SerializeToString,
            kingdoms_dot_v1_dot_game__pb2.MatchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMatchResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kingdoms.v1.Game/GetMatchResult",
            kingdoms_dot_v1_dot_game__pb2.GetMatchResultRequest.SerializeToString,
            kingdoms_dot_v1_dot_game__pb2.MatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kingdoms.v1.Game/GetPlayerStats",
            kingdoms_dot_v1_dot_game__pb2.GetPlayerStatsRequest.SerializeToString,
            kingdoms_dot_v1_dot_game__pb2.PlayerStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMatchLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kingdoms.v1.Game/GetMatchLinks",
            kingdoms_dot_v1_dot_game__pb2.GetMatchLinksRequest.SerializeToString,
            kingdoms_dot_v1_dot_game__pb2.MatchLinks.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMatchDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kingdoms.v1.Game/GetMatchDetails",
            kingdoms_dot_v1_dot_game__pb2.GetMatchDetailsRequest.SerializeToString,
            kingdoms_dot_v1_dot_game__pb2.MatchDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMaps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kingdoms.v1.Game/ListMaps",
            kingdoms_dot_v1_dot_game__pb2.ListMapsRequest.SerializeToString,
            kingdoms_dot_v1_dot_game__pb2.GameMaps.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
