# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from kingdoms.rpc_generated.kingdoms.v1 import live_pb2 as kingdoms_dot_v1_dot_live__pb2

GRPC_GENERATED_VERSION = "1.84.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in kingdoms/v1/live_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class LiveStub:
    """Live test dashboard (kingdoms-services#147): svc-core aggregates the
    provider event streams (ext-aoe2lobby live layer, ext-librematch as the
    source of truth) and serves the per-player dashboard state to the bot.
    The bot renders it through /live in a dedicated channel.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchDashboard = channel.unary_stream(
            "/kingdoms.v1.Live/WatchDashboard",
            request_serializer=kingdoms_dot_v1_dot_live__pb2.WatchDashboardRequest.SerializeToString,
            response_deserializer=kingdoms_dot_v1_dot_live__pb2.DashboardState.FromString,
            _registered_method=True,
        )


class LiveServicer:
    """Live test dashboard (kingdoms-services#147): svc-core aggregates the
    provider event streams (ext-aoe2lobby live layer, ext-librematch as the
    source of truth) and serves the per-player dashboard state to the bot.
    The bot renders it through /live in a dedicated channel.

    """

    def WatchDashboard(self, request, context):
        """Server-stream the current dashboard state: one snapshot immediately,
        then a new snapshot on every aggregated state change.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LiveServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "WatchDashboard": grpc.unary_stream_rpc_method_handler(
            servicer.WatchDashboard,
            request_deserializer=kingdoms_dot_v1_dot_live__pb2.WatchDashboardRequest.FromString,
            response_serializer=kingdoms_dot_v1_dot_live__pb2.DashboardState.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("kingdoms.v1.Live", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("kingdoms.v1.Live", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Live:
    """Live test dashboard (kingdoms-services#147): svc-core aggregates the
    provider event streams (ext-aoe2lobby live layer, ext-librematch as the
    source of truth) and serves the per-player dashboard state to the bot.
    The bot renders it through /live in a dedicated channel.

    """

    @staticmethod
    def WatchDashboard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/kingdoms.v1.Live/WatchDashboard",
            kingdoms_dot_v1_dot_live__pb2.WatchDashboardRequest.SerializeToString,
            kingdoms_dot_v1_dot_live__pb2.DashboardState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
