# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kingdoms/v1/live.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'kingdoms/v1/live.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16kingdoms/v1/live.proto\x12\x0bkingdoms.v1\"8\n\x15WatchDashboardRequest\x12\x10\n\x08game_key\x18\x01 \x01(\t\x12\r\n\x05since\x18\x02 \x01(\x03\"c\n\x0e\x44\x61shboardState\x12)\n\x07players\x18\x01 \x03(\x0b\x32\x18.kingdoms.v1.PlayerState\x12\x14\n\x0cgenerated_at\x18\x02 \x01(\x03\x12\x10\n\x08\x64\x65graded\x18\x03 \x01(\x08\"c\n\x0bPlayerState\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nprofile_id\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x11\n\tmatch_ref\x18\x04 \x01(\t\x12\r\n\x05since\x18\x05 \x01(\x03\x32[\n\x04Live\x12S\n\x0eWatchDashboard\x12\".kingdoms.v1.WatchDashboardRequest\x1a\x1b.kingdoms.v1.DashboardState0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kingdoms.v1.live_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WATCHDASHBOARDREQUEST']._serialized_start=39
  _globals['_WATCHDASHBOARDREQUEST']._serialized_end=95
  _globals['_DASHBOARDSTATE']._serialized_start=97
  _globals['_DASHBOARDSTATE']._serialized_end=196
  _globals['_PLAYERSTATE']._serialized_start=198
  _globals['_PLAYERSTATE']._serialized_end=297
  _globals['_LIVE']._serialized_start=299
  _globals['_LIVE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
